spring:
  datasource:
    mongodb:
      uri: mongodb://wefe:********@*.1.0.*:37017/wefe_union
      databaseName: wefe_union

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 20MB


server:
  port: 9527
  tomcat:
    max-threads: 200
    max-connections: 10000
  servlet:
    context-path: /blockchain-data-sync

sdk:
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 100
  ip: 10.**.**.87
  channelPort: 20200
  certPath: xx/xx/cert  # cert path of relative or absolute


logging:
  config: classpath:log4j2.xml
  level:
    com.welab.wefe: info


wechat:
  bot-url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=

contract:
  data-sync-group-id: 1
  solidity-path: union/blockchain-data-sync/solidity
